[package]
name = "albumseq_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
albumseq = { git = "https://github.com/Thunor12/albumseq.git", branch = "main" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
